<form action="<?= $block->getPostUrl() ?>" method="POST">
    <label for="fName">Enter your first name</label>
    <input name="fName" type="text" id="fName" required>

    <label for="lName">Enter your last name</label>
    <input name="lName" type="text" id="lName" required>

    <label for="email">Enter your email address</label>
    <input name="email" type="email" id="email" required>

    <label for="address">Enter your address</label>
    <textarea name="address" id="address" cols="5" rows="5" required></textarea>

    <label for="phone">Enter your phone</label>
    <input name="phone" type="text" id="phone" required>

    <br /><br />

    <input type="submit" value="SUBMIT" class="action primary">
</form>